name: Release to Marketplace

# Trigger on release creation (only for version tags like v1.0.0, not build tags like v1.0.0-build.1)
# Note: This workflow is kept for compatibility with manual releases.
# For automated releases, use the "Publish to Marketplace" workflow dispatch.
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only run for version tags (e.g., v1.0.0), not build tags (e.g., v1.0.0-build.1)
    if: ${{ !contains(github.event.release.tag_name, '-build.') }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Update package.json version to match release tag
      - name: Update package version
        run: |
          # Extract version from release tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          
          # Update package.json version
          npm version $VERSION --no-git-tag-version
          
          echo "Updated package.json to version: $VERSION"
        env:
          GITHUB_REF: ${{ github.ref }}

      # Build the extension
      - name: Build extension
        run: npm run package

      # Publish to VS Code Marketplace
      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./

      # Publish to Open VSX Registry (alternative marketplace)
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          packagePath: ./
        continue-on-error: true